services:
  backend:
    image: ${BACKEND_IMAGE:?BACKEND_IMAGE is required}
    build: !reset null
    pull_policy: always

  front:
    image: ${FRONT_IMAGE:?FRONT_IMAGE is required}
    build: !reset null
    pull_policy: always
