services:
  backend:
    image: ${BACKEND_IMAGE:?BACKEND_IMAGE is required}
    build: !reset null
    pull_policy: ${PULL_POLICY:-always}

  front:
    image: ${FRONT_IMAGE:?FRONT_IMAGE is required}
    build: !reset null
    pull_policy: ${PULL_POLICY:-always}

  migrate:
    image: ${MIGRATE_IMAGE:?MIGRATE_IMAGE is required}
    build: !reset null
    pull_policy: ${PULL_POLICY:-always}
